image: docker:stable
services:
- docker:dind

stages:
- build
- test
- release
- trigger

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/aem-base:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/aem-base:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CONTAINER_TEST_IMAGE" .
    - docker push "$CONTAINER_TEST_IMAGE"

test:
  stage: test
  script:
    - docker run $CONTAINER_TEST_IMAGE convert -version

release-image:
  stage: release
  script:
    - docker pull "$CONTAINER_TEST_IMAGE"
    - docker tag "$CONTAINER_TEST_IMAGE" "$CONTAINER_RELEASE_IMAGE"
    - docker push "$CONTAINER_RELEASE_IMAGE"
  only:
    - master

trigger_build:
  stage: trigger
  script:
    - echo "Build aem:latest"
    - docker run appropriate/curl curl -X POST -F "token=21c18668aeeadd75cfb91102d27338" -F "ref=$CI_COMMIT_REF_NAME" https://gitlab.com/api/v4/projects/7634356/trigger/pipeline
    - echo "Build aem:6.4.0"
    - docker run appropriate/curl curl -X POST -F "token=21c18668aeeadd75cfb91102d27338" -F "ref=6.4.0" https://gitlab.com/api/v4/projects/7634356/trigger/pipeline
